<?php

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();

$enabled = $objectManager->get('Magento\Framework\App\Config\ScopeConfigInterface')->getValue('dipi_configuration/general/enabled') ?? false;
$token = $objectManager->get('Magento\Framework\App\Config\ScopeConfigInterface')->getValue('dipi_configuration/general/token') ?? false;
$brandId = $objectManager->get('Magento\Framework\App\Config\ScopeConfigInterface')->getValue('dipi_configuration/general/brand_id') ?? false;
$dipi = isset($_GET['dipi']) ? $_GET['dipi'] : false;

if ($enabled && $brandId && $token && $dipi) {
    // Fix for Cloudflare
    if (isset($_SERVER["HTTP_CF_CONNECTING_IP"])) {
        $_SERVER['REMOTE_ADDR'] = $_SERVER["HTTP_CF_CONNECTING_IP"];
    }

    if (!isset($_COOKIE['dp_' . $brandId])) {
        setcookie('dp_' . $brandId, md5(uniqid()), time() + (86400 * 30), '/');
    }

    $data = array(
        'token' => $token,
        'dipi' => $dipi,
        'ip_address' => $_SERVER['REMOTE_ADDR'],
        'user_agent' => $_SERVER['HTTP_USER_AGENT'],
        'cookie' => isset($_COOKIE['dp_' . $brandId]) ? $_COOKIE['dp_' . $brandId] : null,
    );
    
    $ch = curl_init('https://dipi.io/t/s2s/click/' . $brandId);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, false);
    curl_setopt($ch, CURLOPT_POSTFIELDS, $post);
    curl_exec($ch);
    curl_close($ch);
}