<?php

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();

$enabled = $objectManager->get('Magento\Framework\App\Config\ScopeConfigInterface')->getValue('dipi_configuration/general/enabled') ?? false;
$token = $objectManager->get('Magento\Framework\App\Config\ScopeConfigInterface')->getValue('dipi_configuration/general/token') ?? false;
$brandId = $objectManager->get('Magento\Framework\App\Config\ScopeConfigInterface')->getValue('dipi_configuration/general/brand_id') ?? false;
$orderId = $this->getOrderId();

if ($enabled && $orderId && $brandId && $token) {
    // Fix for Cloudflare
    if ( isset( $_SERVER["HTTP_CF_CONNECTING_IP"] ) ) {
        $_SERVER['REMOTE_ADDR'] = $_SERVER["HTTP_CF_CONNECTING_IP"];
    }

    $order = $objectManager->create('Magento\Sales\Model\Order')->load($orderId);

    $data = array(
        'token' => $token,
        'reference' => $orderId,
        'amount' => $order->getGrandTotal(),
        'currency' => $order->getOrderCurrencyCode(),
        'discount_code' => $order->getCouponCode(),
        'user_agent' => $_SERVER['HTTP_USER_AGENT'],
        'ip_address' => $_SERVER['REMOTE_ADDR'],
        'cookie' => isset($_COOKIE['dp_' . $brandId]) ? $_COOKIE['dp_' . $brandId] : null,
        'new_customer' => ($order->getCustomerId() > 0 ? 1 : 0),
    );
    
    $ch = curl_init('https://dipi.io/t/s2s/sale/' . $brandId);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, false);
    curl_setopt($ch, CURLOPT_POSTFIELDS, $post);
    curl_exec($ch);
    curl_close($ch);
}